
START_MENU_01_L00 : string "########################################"
START_MENU_01_L01 : string "#                             @@@    @ #"
START_MENU_01_L02 : string "#  ###  #   ##  #     ##   #    @   @  #"
START_MENU_01_L03 : string "#   #  # # #   # #    # # # #  @       #"
START_MENU_01_L04 : string "#    # # # # # # #    # # ###       @  #"
START_MENU_01_L05 : string "#  # # # # # # # #    # # # #  @    @@ #"
START_MENU_01_L06 : string "#   #   #   #   #     ##  # #  @@  @ @ #"
START_MENU_01_L07 : string "#                             @ @      #"
START_MENU_01_L08 : string "#  # # # ##   #                        #"
START_MENU_01_L09 : string "#  # # # # # # #                    @@ #"
START_MENU_01_L10 : string "#  # # # # # ###               @@  @ @ #"
START_MENU_01_L11 : string "#  # # # # # # #          @@  @ @    @ #"
START_MENU_01_L12 : string "#   #  # ##  # #         @ @    @      #"
START_MENU_01_L13 : string "#                          @           #"
START_MENU_01_L14 : string "#  -> Pressione a tecla             @@ #"
START_MENU_01_L15 : string "#  ENTER para continuar        @@    @@#"
START_MENU_01_L16 : string "#                         @@    @@  @  #"
START_MENU_01_L17 : string "# @    @             @@    @@  @       #"
START_MENU_01_L18 : string "# @             @@    @@  @            #"
START_MENU_01_L19 : string "#          @@    @@  @              @@@#"
START_MENU_01_L20 : string "#     @@    @@  @              @@@    @#"
START_MENU_01_L21 : string "#@@    @@  @              @@@    @   @ #"
START_MENU_01_L22 : string "# @@  @              @@@    @   @      #"
START_MENU_01_L23 : string "#@              @@@    @   @         @ #"
START_MENU_01_L24 : string "#          @@@    @   @         @    @@#"
START_MENU_01_L25 : string "#     @@@    @   @         @    @@  @ @#"
START_MENU_01_L26 : string "#@@@    @   @         @    @@  @ @     #"
START_MENU_01_L27 : string "#  @   @         @    @@  @ @          #"
START_MENU_01_L28 : string "# @         @    @@  @ @            @@@#"
START_MENU_01_L29 : string "########################################"

START_MENU_02_L00 : string "########################################"
START_MENU_02_L01 : string "#                              @@   @ @#"
START_MENU_02_L02 : string "#  ###  #   ##  #     ##   #  @ @      #"
START_MENU_02_L03 : string "#   #  # # #   # #    # # # #          #"
START_MENU_02_L04 : string "#    # # # # # # #    # # ###       @@ #"
START_MENU_02_L05 : string "#  # # # # # # # #    # # # #  @@  @ @ #"
START_MENU_02_L06 : string "#   #   #   #   #     ##  # # @ @    @ #"
START_MENU_02_L07 : string "#                               @      #"
START_MENU_02_L08 : string "#  # # # ##   #                        #"
START_MENU_02_L09 : string "#  # # # # # # #                    @@ #"
START_MENU_02_L10 : string "#  # # # # # ###               @@    @@#"
START_MENU_02_L11 : string "#  # # # # # # #          @@    @@  @  #"
START_MENU_02_L12 : string "#   #  # ##  # #           @@  @       #"
START_MENU_02_L13 : string "#                         @            #"
START_MENU_02_L14 : string "#  -> Pressione a tecla             @@@#"
START_MENU_02_L15 : string "#  _____ para continuar        @@@    @#"
START_MENU_02_L16 : string "#                         @@@    @   @ #"
START_MENU_02_L17 : string "# @@  @              @@@    @   @      #"
START_MENU_02_L18 : string "#@              @@@    @   @         @ #"
START_MENU_02_L19 : string "#          @@@    @   @         @    @@#"
START_MENU_02_L20 : string "#     @@@    @   @         @    @@  @ @#"
START_MENU_02_L21 : string "#@@@    @   @         @    @@  @ @     #"
START_MENU_02_L22 : string "#  @   @         @    @@  @ @          #"
START_MENU_02_L23 : string "# @         @    @@  @ @             @@#"
START_MENU_02_L24 : string "#      @    @@  @ @             @@  @ @#"
START_MENU_02_L25 : string "# @    @@  @ @             @@  @ @    @#"
START_MENU_02_L26 : string "# @@  @ @             @@  @ @    @     #"
START_MENU_02_L27 : string "#@ @             @@  @ @    @        @ #"
START_MENU_02_L28 : string "#           @@  @ @    @             @@#"
START_MENU_02_L29 : string "########################################"

START_MENU_03_L00 : string "########################################"
START_MENU_03_L01 : string "#                               @    @ #"
START_MENU_03_L02 : string "#  ###  #   ##  #     ##   #   @       #"
START_MENU_03_L03 : string "#   #  # # #   # #    # # # #          #"
START_MENU_03_L04 : string "#    # # # # # # #    # # ###       @@ #"
START_MENU_03_L05 : string "#  # # # # # # # #    # # # #  @@    @@#"
START_MENU_03_L06 : string "#   #   #   #   #     ##  # #   @@  @  #"
START_MENU_03_L07 : string "#                              @       #"
START_MENU_03_L08 : string "#  # # # ##   #                        #"
START_MENU_03_L09 : string "#  # # # # # # #                    @@@#"
START_MENU_03_L10 : string "#  # # # # # ###               @@@    @#"
START_MENU_03_L11 : string "#  # # # # # # #          @@@    @   @ #"
START_MENU_03_L12 : string "#   #  # ##  # #            @   @      #"
START_MENU_03_L13 : string "#                          @         @ #"
START_MENU_03_L14 : string "#  -> Pressione a tecla         @    @@#"
START_MENU_03_L15 : string "#  ENTER para continuar    @    @@  @ @#"
START_MENU_03_L16 : string "#                          @@  @ @     #"
START_MENU_03_L17 : string "# @@  @          @    @@  @ @          #"
START_MENU_03_L18 : string "#@          @    @@  @ @             @@#"
START_MENU_03_L19 : string "#      @    @@  @ @             @@  @ @#"
START_MENU_03_L20 : string "# @    @@  @ @             @@  @ @    @#"
START_MENU_03_L21 : string "# @@  @ @             @@  @ @    @     #"
START_MENU_03_L22 : string "#@ @             @@  @ @    @          #"
START_MENU_03_L23 : string "#           @@  @ @    @             @@#"
START_MENU_03_L24 : string "#      @@  @ @    @             @@    @#"
START_MENU_03_L25 : string "# @@  @ @    @             @@    @@  @ #"
START_MENU_03_L26 : string "#@ @    @             @@    @@  @      #"
START_MENU_03_L27 : string "#  @             @@    @@  @         @@#"
START_MENU_03_L28 : string "#           @@    @@  @             @ @#"
START_MENU_03_L29 : string "########################################"

START_MENU_04_L00 : string "########################################"
START_MENU_04_L01 : string "#                              @ @  @ @#"
START_MENU_04_L02 : string "#  ###  #   ##  #     ##   #     @     #"
START_MENU_04_L03 : string "#   #  # # #   # #    # # # #          #"
START_MENU_04_L04 : string "#    # # # # # # #    # # ###       @@@#"
START_MENU_04_L05 : string "#  # # # # # # # #    # # # #  @@@    @#"
START_MENU_04_L06 : string "#   #   #   #   #     ##  # #    @   @ #"
START_MENU_04_L07 : string "#                               @      #"
START_MENU_04_L08 : string "#  # # # ##   #                      @ #"
START_MENU_04_L09 : string "#  # # # # # # #                @    @@#"
START_MENU_04_L10 : string "#  # # # # # ###           @    @@  @ @#"
START_MENU_04_L11 : string "#  # # # # # # #           @@  @ @     #"
START_MENU_04_L12 : string "#   #  # ##  # #          @ @          #"
START_MENU_04_L13 : string "#                                    @@#"
START_MENU_04_L14 : string "#  -> Pressione a tecla         @@  @ @#"
START_MENU_04_L15 : string "#  _____ para continuar    @@  @ @    @#"
START_MENU_04_L16 : string "#                         @ @    @     #"
START_MENU_04_L17 : string "# @@  @          @@  @ @    @          #"
START_MENU_04_L18 : string "#@          @@  @ @    @             @@#"
START_MENU_04_L19 : string "#      @@  @ @    @             @@    @#"
START_MENU_04_L20 : string "# @@  @ @    @             @@    @@  @ #"
START_MENU_04_L21 : string "#@ @    @             @@    @@  @      #"
START_MENU_04_L22 : string "#  @             @@    @@  @           #"
START_MENU_04_L23 : string "#           @@    @@  @              @@#"
START_MENU_04_L24 : string "#      @@    @@  @              @@@    #"
START_MENU_04_L25 : string "# @@    @@  @              @@@    @   @#"
START_MENU_04_L26 : string "#  @@  @              @@@    @   @     #"
START_MENU_04_L27 : string "# @              @@@    @   @        @@#"
START_MENU_04_L28 : string "#           @@@    @   @             @ #"
START_MENU_04_L29 : string "########################################"
