
START_MENU_01_L00 : string "########################################"
START_MENU_01_L01 : string "#                             @@@    @ #"
START_MENU_01_L02 : string "#  ###  #   ##  #     ##   #    @   @  #"
START_MENU_01_L03 : string "#   #  # # #   # #    # # # #  @       #"
START_MENU_01_L04 : string "#    # # # # # # #    # # ###       @  #"
START_MENU_01_L05 : string "#  # # # # # # # #    # # # #  @    @@ #"
START_MENU_01_L06 : string "#   #   #   #   #     ##  # #  @@  @ @ #"
START_MENU_01_L07 : string "#                             @ @      #"
START_MENU_01_L08 : string "#  # # # ##   #                        #"
START_MENU_01_L09 : string "#  # # # # # # #                    @@ #"
START_MENU_01_L10 : string "#  # # # # # ###               @@  @ @ #"
START_MENU_01_L11 : string "#  # # # # # # #          @@  @ @    @ #"
START_MENU_01_L12 : string "#   #  # ##  # #         @ @    @      #"
START_MENU_01_L13 : string "#                          @           #"
START_MENU_01_L14 : string "#  -> Pressione a tecla             @@ #"
START_MENU_01_L15 : string "#  ENTER para continuar        @@    @@#"
START_MENU_01_L16 : string "#                         @@    @@  @  #"
START_MENU_01_L17 : string "#                    @@    @@  @       #"
START_MENU_01_L18 : string "#               @@    @@  @            #"
START_MENU_01_L19 : string "#          @@    @@  @              @@@#"
START_MENU_01_L20 : string "#     @@    @@  @              @@@    @#"
START_MENU_01_L21 : string "#@@    @@  @              @@@    @   @ #"
START_MENU_01_L22 : string "# @@  @              @@@    @   @      #"
START_MENU_01_L23 : string "#@              @@@    @   @         @ #"
START_MENU_01_L24 : string "#          @@@    @   @         @    @@#"
START_MENU_01_L25 : string "#     @@@    @   @         @    @@  @ @#"
START_MENU_01_L26 : string "#@@@    @   @         @    @@  @ @     #"
START_MENU_01_L27 : string "#  @   @         @    @@  @ @          #"
START_MENU_01_L28 : string "# @         @    @@  @ @            @@@#"
START_MENU_01_L29 : string "########################################"

START_MENU_02_L00 : string "########################################"
START_MENU_02_L01 : string "#                              @@   @ @#"
START_MENU_02_L02 : string "#  ###  #   ##  #     ##   #  @ @      #"
START_MENU_02_L03 : string "#   #  # # #   # #    # # # #          #"
START_MENU_02_L04 : string "#    # # # # # # #    # # ###       @@ #"
START_MENU_02_L05 : string "#  # # # # # # # #    # # # #  @@  @ @ #"
START_MENU_02_L06 : string "#   #   #   #   #     ##  # # @ @    @ #"
START_MENU_02_L07 : string "#                               @      #"
START_MENU_02_L08 : string "#  # # # ##   #                        #"
START_MENU_02_L09 : string "#  # # # # # # #                    @@ #"
START_MENU_02_L10 : string "#  # # # # # ###               @@    @@#"
START_MENU_02_L11 : string "#  # # # # # # #          @@    @@  @  #"
START_MENU_02_L12 : string "#   #  # ##  # #           @@  @       #"
START_MENU_02_L13 : string "#                         @            #"
START_MENU_02_L14 : string "#  -> Pressione a tecla             @@@#"
START_MENU_02_L15 : string "#  _____ para continuar        @@@    @#"
START_MENU_02_L16 : string "#                         @@@    @   @ #"
START_MENU_02_L17 : string "#                    @@@    @   @      #"
START_MENU_02_L18 : string "#               @@@    @   @         @ #"
START_MENU_02_L19 : string "#          @@@    @   @         @    @@#"
START_MENU_02_L20 : string "#     @@@    @   @         @    @@  @ @#"
START_MENU_02_L21 : string "#@@@    @   @         @    @@  @ @     #"
START_MENU_02_L22 : string "#  @   @         @    @@  @ @          #"
START_MENU_02_L23 : string "# @         @    @@  @ @             @@#"
START_MENU_02_L24 : string "#      @    @@  @ @             @@  @ @#"
START_MENU_02_L25 : string "# @    @@  @ @             @@  @ @    @#"
START_MENU_02_L26 : string "# @@  @ @             @@  @ @    @     #"
START_MENU_02_L27 : string "#@ @             @@  @ @    @        @ #"
START_MENU_02_L28 : string "#           @@  @ @    @             @@#"
START_MENU_02_L29 : string "########################################"

START_MENU_03_L00 : string "########################################"
START_MENU_03_L01 : string "#                               @    @ #"
START_MENU_03_L02 : string "#  ###  #   ##  #     ##   #   @       #"
START_MENU_03_L03 : string "#   #  # # #   # #    # # # #          #"
START_MENU_03_L04 : string "#    # # # # # # #    # # ###       @@ #"
START_MENU_03_L05 : string "#  # # # # # # # #    # # # #  @@    @@#"
START_MENU_03_L06 : string "#   #   #   #   #     ##  # #   @@  @  #"
START_MENU_03_L07 : string "#                              @       #"
START_MENU_03_L08 : string "#  # # # ##   #                        #"
START_MENU_03_L09 : string "#  # # # # # # #                    @@@#"
START_MENU_03_L10 : string "#  # # # # # ###               @@@    @#"
START_MENU_03_L11 : string "#  # # # # # # #          @@@    @   @ #"
START_MENU_03_L12 : string "#   #  # ##  # #            @   @      #"
START_MENU_03_L13 : string "#                          @         @ #"
START_MENU_03_L14 : string "#  -> Pressione a tecla         @    @@#"
START_MENU_03_L15 : string "#  ENTER para continuar    @    @@  @ @#"
START_MENU_03_L16 : string "#                          @@  @ @     #"
START_MENU_03_L17 : string "#                @    @@  @ @          #"
START_MENU_03_L18 : string "#           @    @@  @ @             @@#"
START_MENU_03_L19 : string "#      @    @@  @ @             @@  @ @#"
START_MENU_03_L20 : string "# @    @@  @ @             @@  @ @    @#"
START_MENU_03_L21 : string "# @@  @ @             @@  @ @    @     #"
START_MENU_03_L22 : string "#@ @             @@  @ @    @          #"
START_MENU_03_L23 : string "#           @@  @ @    @             @@#"
START_MENU_03_L24 : string "#      @@  @ @    @             @@    @#"
START_MENU_03_L25 : string "# @@  @ @    @             @@    @@  @ #"
START_MENU_03_L26 : string "#@ @    @             @@    @@  @      #"
START_MENU_03_L27 : string "#  @             @@    @@  @         @@#"
START_MENU_03_L28 : string "#           @@    @@  @             @ @#"
START_MENU_03_L29 : string "########################################"

START_MENU_04_L00 : string "########################################"
START_MENU_04_L01 : string "#                              @ @  @ @#"
START_MENU_04_L02 : string "#  ###  #   ##  #     ##   #     @     #"
START_MENU_04_L03 : string "#   #  # # #   # #    # # # #          #"
START_MENU_04_L04 : string "#    # # # # # # #    # # ###       @@@#"
START_MENU_04_L05 : string "#  # # # # # # # #    # # # #  @@@    @#"
START_MENU_04_L06 : string "#   #   #   #   #     ##  # #    @   @ #"
START_MENU_04_L07 : string "#                               @      #"
START_MENU_04_L08 : string "#  # # # ##   #                      @ #"
START_MENU_04_L09 : string "#  # # # # # # #                @    @@#"
START_MENU_04_L10 : string "#  # # # # # ###           @    @@  @ @#"
START_MENU_04_L11 : string "#  # # # # # # #           @@  @ @     #"
START_MENU_04_L12 : string "#   #  # ##  # #          @ @          #"
START_MENU_04_L13 : string "#                                    @@#"
START_MENU_04_L14 : string "#  -> Pressione a tecla         @@  @ @#"
START_MENU_04_L15 : string "#  _____ para continuar    @@  @ @    @#"
START_MENU_04_L16 : string "#                         @ @    @     #"
START_MENU_04_L17 : string "#                @@  @ @    @          #"
START_MENU_04_L18 : string "#           @@  @ @    @             @@#"
START_MENU_04_L19 : string "#      @@  @ @    @             @@    @#"
START_MENU_04_L20 : string "# @@  @ @    @             @@    @@  @ #"
START_MENU_04_L21 : string "#@ @    @             @@    @@  @      #"
START_MENU_04_L22 : string "#  @             @@    @@  @           #"
START_MENU_04_L23 : string "#           @@    @@  @              @@#"
START_MENU_04_L24 : string "#      @@    @@  @              @@@    #"
START_MENU_04_L25 : string "# @@    @@  @              @@@    @   @#"
START_MENU_04_L26 : string "#  @@  @              @@@    @   @     #"
START_MENU_04_L27 : string "# @              @@@    @   @        @@#"
START_MENU_04_L28 : string "#           @@@    @   @             @ #"
START_MENU_04_L29 : string "########################################"

SCENARIO_SELECTION_MENU_L00 : string "########################################"
SCENARIO_SELECTION_MENU_L01 : string "#                                      #"
SCENARIO_SELECTION_MENU_L02 : string "#                                      #"
SCENARIO_SELECTION_MENU_L03 : string "#                                      #"
SCENARIO_SELECTION_MENU_L04 : string "#                                      #"
SCENARIO_SELECTION_MENU_L05 : string "#                                      #"
SCENARIO_SELECTION_MENU_L06 : string "#                                      #"
SCENARIO_SELECTION_MENU_L07 : string "#                                      #"
SCENARIO_SELECTION_MENU_L08 : string "#             Selecione um             #"
SCENARIO_SELECTION_MENU_L09 : string "#               cenario                #"
SCENARIO_SELECTION_MENU_L10 : string "#                                      #"
SCENARIO_SELECTION_MENU_L11 : string "#                                      #"
SCENARIO_SELECTION_MENU_L12 : string "# -> 01. Chaos                         #"
SCENARIO_SELECTION_MENU_L13 : string "#    02. Symmetrical oscillators       #"
SCENARIO_SELECTION_MENU_L14 : string "#    03. Still lifes and oscillators   #"
SCENARIO_SELECTION_MENU_L15 : string "#    04. Symmetrical oscillators 2     #"
SCENARIO_SELECTION_MENU_L16 : string "#    05. Symmetrical stuck             #"
SCENARIO_SELECTION_MENU_L17 : string "#    06. Chaos 2                       #"
SCENARIO_SELECTION_MENU_L18 : string "#    07. Gosper's glider gun           #"
SCENARIO_SELECTION_MENU_L19 : string "#    08. Custom scenario               #"
SCENARIO_SELECTION_MENU_L20 : string "#                                      #"
SCENARIO_SELECTION_MENU_L21 : string "#                                      #"
SCENARIO_SELECTION_MENU_L22 : string "#                                      #"
SCENARIO_SELECTION_MENU_L23 : string "#                                      #"
SCENARIO_SELECTION_MENU_L24 : string "#                                      #"
SCENARIO_SELECTION_MENU_L25 : string "#                                      #"
SCENARIO_SELECTION_MENU_L26 : string "#                                      #"
SCENARIO_SELECTION_MENU_L27 : string "#                                      #"
SCENARIO_SELECTION_MENU_L28 : string "#                                      #"
SCENARIO_SELECTION_MENU_L29 : string "########################################"
