SCENARIO1_L01: string "                                        "
SCENARIO1_L02: string "                                        "
SCENARIO1_L03: string "                                        "
SCENARIO1_L04: string "                                        "
SCENARIO1_L05: string "                                        "
SCENARIO1_L06: string "                                        "
SCENARIO1_L07: string "                                        "
SCENARIO1_L08: string "                                        "
SCENARIO1_L09: string "                                        "
SCENARIO1_L10: string "                                        "
SCENARIO1_L11: string "                                        "
SCENARIO1_L12: string "                                        "
SCENARIO1_L13: string "                                        "
SCENARIO1_L14: string "                                        "
SCENARIO1_L15: string "                                        "
SCENARIO1_L16: string "                                        "
SCENARIO1_L17: string "               @                        "
SCENARIO1_L18: string "              @@                        "
SCENARIO1_L19: string "               @@                       "
SCENARIO1_L20: string "                                        "
SCENARIO1_L21: string "                                        "
SCENARIO1_L22: string "                                        "
SCENARIO1_L23: string "                                        "
SCENARIO1_L24: string "                                        "
SCENARIO1_L25: string "                                        "
SCENARIO1_L26: string "                                        "
SCENARIO1_L27: string "                                        "
SCENARIO1_L28: string "                                        "
SCENARIO1_L29: string "                                        "
SCENARIO1_L30: string "                                        "
