CENARIO1_L01: string "                                        "
CENARIO1_L02: string "                                        "
CENARIO1_L03: string "    @@  @@                              "
CENARIO1_L04: string "    @    @                              "
CENARIO1_L05: string "                        @@@             "
CENARIO1_L06: string "                                        "
CENARIO1_L07: string "    @    @                              "
CENARIO1_L08: string "    @@  @@                              "
CENARIO1_L09: string "                                        "
CENARIO1_L10: string "                                        "
CENARIO1_L11: string "                                        "
CENARIO1_L12: string "                                        "
CENARIO1_L13: string "                                        "
CENARIO1_L14: string "                                        "
CENARIO1_L15: string "         @@@                            "
CENARIO1_L16: string "         @                              "
CENARIO1_L17: string "          @                             "
CENARIO1_L18: string "                                        "
CENARIO1_L19: string "                                        "
CENARIO1_L20: string "                        @@@             "
CENARIO1_L21: string "                        @ @             "
CENARIO1_L22: string "                        @@@             "
CENARIO1_L23: string "                                        "
CENARIO1_L24: string "                                        "
CENARIO1_L25: string "                                        "
CENARIO1_L26: string "                                        "
CENARIO1_L27: string "                                        "
CENARIO1_L28: string "                                        "
CENARIO1_L29: string "                                        "
CENARIO1_L30: string "                                        "
