;; Gosper's glider gun

SCENARIO7_L01: string "                         @              "
SCENARIO7_L02: string "                       @ @              "
SCENARIO7_L03: string "             @@      @@            @@   "
SCENARIO7_L04: string "            @   @    @@            @@   "
SCENARIO7_L05: string " @@        @     @   @@                 "
SCENARIO7_L06: string " @@        @   @ @@    @ @              "
SCENARIO7_L07: string "           @     @       @              "
SCENARIO7_L08: string "            @   @                       "
SCENARIO7_L09: string "             @@                         "
SCENARIO7_L10: string "                                        "
SCENARIO7_L11: string "                                        "
SCENARIO7_L12: string "                                        "
SCENARIO7_L13: string "                                        "
SCENARIO7_L14: string "                                        "
SCENARIO7_L15: string "                                        "
SCENARIO7_L16: string "                                        "
SCENARIO7_L17: string "                                        "
SCENARIO7_L18: string "                                        "
SCENARIO7_L19: string "                                        "
SCENARIO7_L20: string "                                        "
SCENARIO7_L21: string "                                        "
SCENARIO7_L22: string "                                        "
SCENARIO7_L23: string "                                        "
SCENARIO7_L24: string "                                        "
SCENARIO7_L25: string "                                        "
SCENARIO7_L26: string "                                        "
SCENARIO7_L27: string "                                        "
SCENARIO7_L28: string "                                        "
SCENARIO7_L29: string "                                        "
SCENARIO7_L30: string "                                        "