;; Simmetrical ocillators 2

SCENARIO4_L01: string "                                        "
SCENARIO4_L02: string "                                        "
SCENARIO4_L03: string "                                        "
SCENARIO4_L04: string "                                        "
SCENARIO4_L05: string "                 @@@                    "
SCENARIO4_L06: string "                                        "
SCENARIO4_L07: string "               @  @  @                  "
SCENARIO4_L08: string "               @ @@@ @                  "
SCENARIO4_L09: string "               @     @                  "
SCENARIO4_L10: string "                                        "
SCENARIO4_L11: string "                 @@@                    "
SCENARIO4_L12: string "          @@@           @@@             "
SCENARIO4_L13: string "                                        "
SCENARIO4_L14: string "        @  @  @   @   @  @  @           "
SCENARIO4_L15: string "        @ @@  @  @@@  @  @@ @           "
SCENARIO4_L16: string "        @  @  @   @   @  @  @           "
SCENARIO4_L17: string "                                        "
SCENARIO4_L18: string "          @@@    @@@    @@@             "
SCENARIO4_L19: string "                                        "
SCENARIO4_L20: string "               @     @                  "
SCENARIO4_L21: string "               @ @@@ @                  "
SCENARIO4_L22: string "               @  @  @                  "
SCENARIO4_L23: string "                                        "
SCENARIO4_L24: string "                 @@@                    "
SCENARIO4_L25: string "                                        "
SCENARIO4_L26: string "                                        "
SCENARIO4_L27: string "                                        "
SCENARIO4_L28: string "                                        "
SCENARIO4_L29: string "                                        "
SCENARIO4_L30: string "                                        "
