;; Symmetrical blinkers

SCENARIO2_L01: string "                                        "
SCENARIO2_L02: string "                                        "
SCENARIO2_L03: string "                                        "
SCENARIO2_L04: string "                                        "
SCENARIO2_L05: string "                                        "
SCENARIO2_L06: string "                                        "
SCENARIO2_L07: string "                                        "
SCENARIO2_L08: string "                                        "
SCENARIO2_L09: string "                                        "
SCENARIO2_L10: string "                                        "
SCENARIO2_L11: string "                                        "
SCENARIO2_L12: string "                                        "
SCENARIO2_L13: string "                                        "
SCENARIO2_L14: string "                                        "
SCENARIO2_L15: string "                                        "
SCENARIO2_L16: string "                                        "
SCENARIO2_L17: string "                                        "
SCENARIO2_L18: string "                                        "
SCENARIO2_L19: string "                                        "
SCENARIO2_L20: string "                                        "
SCENARIO2_L21: string "                                        "
SCENARIO2_L22: string "                                        "
SCENARIO2_L23: string "                   @@@                  "
SCENARIO2_L24: string "                   @ @                  "
SCENARIO2_L25: string "                   @ @                  "
SCENARIO2_L26: string "                                        "
SCENARIO2_L27: string "                                        "
SCENARIO2_L28: string "                                        "
SCENARIO2_L29: string "                                        "
SCENARIO2_L30: string "                                        "
