;; Chaos 2

SCENARIO6_L01: string "                                        "
SCENARIO6_L02: string "                                        "                                       
SCENARIO6_L03: string "                                        "
SCENARIO6_L04: string "                                        "
SCENARIO6_L05: string "                                        "
SCENARIO6_L06: string "                                        "
SCENARIO6_L07: string "                                        "
SCENARIO6_L08: string "                                        "
SCENARIO6_L09: string "                                        "
SCENARIO6_L10: string "                                        "
SCENARIO6_L11: string "           @@  @@@                      "
SCENARIO6_L12: string "              @                         "
SCENARIO6_L13: string "            @                           "
SCENARIO6_L14: string "                                        "
SCENARIO6_L15: string "                                        "
SCENARIO6_L16: string "                                        "
SCENARIO6_L17: string "                                        "
SCENARIO6_L18: string "                                        "
SCENARIO6_L19: string "                                        "
SCENARIO6_L20: string "                                        "
SCENARIO6_L21: string "                                        "
SCENARIO6_L22: string "                                        "
SCENARIO6_L23: string "                                        "
SCENARIO6_L24: string "                                        "
SCENARIO6_L25: string "                                        "
SCENARIO6_L26: string "                                        "
SCENARIO6_L27: string "                                        "
SCENARIO6_L28: string "                                        "
SCENARIO6_L29: string "                                        "
SCENARIO6_L30: string "                                        "