; Still lifes and oscillators

SCENARIO3_L01: string " @@    @@    @@    @@    @              "
SCENARIO3_L02: string " @@   @  @  @  @   @ @  @ @             "
SCENARIO3_L03: string "       @@    @ @    @    @              "
SCENARIO3_L04: string "              @                         "
SCENARIO3_L05: string "                                        "
SCENARIO3_L06: string "                     @@                 "
SCENARIO3_L07: string "                     @@                 "
SCENARIO3_L08: string " @@@     @@@           @@               "
SCENARIO3_L09: string "        @@@            @@               "
SCENARIO3_L10: string "                                        "
SCENARIO3_L11: string "                                        "
SCENARIO3_L12: string "                                        "
SCENARIO3_L13: string "                                        "
SCENARIO3_L14: string "                                        "
SCENARIO3_L15: string "                                        "
SCENARIO3_L16: string "    @@@   @@@                           "
SCENARIO3_L17: string "                          @@@           "
SCENARIO3_L18: string "  @    @ @    @            @            "
SCENARIO3_L19: string "  @    @ @    @            @            "
SCENARIO3_L20: string "  @    @ @    @           @@@           "
SCENARIO3_L21: string "    @@@   @@@                           "
SCENARIO3_L22: string "                          @@@           "
SCENARIO3_L23: string "    @@@   @@@             @@@           "
SCENARIO3_L24: string "  @    @ @    @                         "
SCENARIO3_L25: string "  @    @ @    @           @@@           "
SCENARIO3_L26: string "  @    @ @    @            @            "
SCENARIO3_L27: string "                           @            "
SCENARIO3_L28: string "    @@@   @@@             @@@           "
SCENARIO3_L29: string "                                        "
SCENARIO3_L30: string "                                        "
