;; Simmetrical stuck

SCENARIO5_L01: string "                                        "
SCENARIO5_L02: string "                                        "                                       
SCENARIO5_L03: string "                                        "
SCENARIO5_L04: string "                                        "
SCENARIO5_L05: string "                                        "
SCENARIO5_L06: string "                                        "
SCENARIO5_L07: string "                                        "
SCENARIO5_L08: string "                                        "
SCENARIO5_L09: string "                                        "
SCENARIO5_L10: string "                                        "
SCENARIO5_L11: string "                                        "
SCENARIO5_L12: string "                                        "
SCENARIO5_L13: string "                                        "
SCENARIO5_L14: string "               @                        "
SCENARIO5_L15: string "                @@ @                    "
SCENARIO5_L16: string "                @                       "
SCENARIO5_L17: string "                   @                    "
SCENARIO5_L18: string "                @ @@                    "
SCENARIO5_L19: string "                    @                   "
SCENARIO5_L20: string "                                        "
SCENARIO5_L21: string "                                        "
SCENARIO5_L22: string "                                        "
SCENARIO5_L23: string "                                        "
SCENARIO5_L24: string "                                        "
SCENARIO5_L25: string "                                        "
SCENARIO5_L26: string "                                        "
SCENARIO5_L27: string "                                        "
SCENARIO5_L28: string "                                        "
SCENARIO5_L29: string "                                        "
SCENARIO5_L30: string "                                        "